baseURL = "http://accelero.ai.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Accelero.ai"
[markup.goldmark.renderer]
unsafe = true
