
[en]
contentDir = "content/english"
copyright = ""
footer_content = "Accelerating Business"
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Accelero.ai"
weight = 1
